# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='\u05de\u05e1\u05e4\u05e8')),
                ('title', models.CharField(max_length=30, verbose_name='\u05db\u05d5\u05ea\u05e8\u05ea')),
            ],
            options={
                'ordering': ['number'],
                'verbose_name': '\u05e4\u05e8\u05e7',
                'verbose_name_plural': '\u05e4\u05e8\u05e7\u05d9\u05dd',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='\u05d8\u05e7\u05e1\u05d8')),
                ('is_correct', models.BooleanField(default=False, verbose_name='\u05ea\u05e9\u05d5\u05d1\u05ea \u05e0\u05db\u05d5\u05e0\u05d4?')),
            ],
            options={
                'abstract': False,
                'verbose_name': '\u05d1\u05d7\u05d9\u05e8\u05d4',
                'verbose_name_plural': '\u05d1\u05d7\u05d9\u05e8\u05d5\u05ea',
            },
        ),
        migrations.CreateModel(
            name='ChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='\u05de\u05e1\u05e4\u05e8')),
                ('text', models.TextField(verbose_name='\u05d8\u05e7\u05e1\u05d8')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.Chapter', verbose_name='\u05e4\u05e8\u05e7')),
                ('followup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logic.ChoiceQuestion', verbose_name='\u05e9\u05d0\u05dc\u05ea \u05d4\u05de\u05e9\u05da')),
            ],
            options={
                'ordering': ['number'],
                'abstract': False,
                'verbose_name': '\u05e9\u05d0\u05dc\u05ea \u05d1\u05d7\u05d9\u05e8\u05d4',
                'verbose_name_plural': '\u05e9\u05d0\u05dc\u05d5\u05ea \u05d1\u05d7\u05d9\u05e8\u05d4',
            },
        ),
        migrations.CreateModel(
            name='DeductionQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='\u05de\u05e1\u05e4\u05e8')),
                ('formula', models.CharField(max_length=30, verbose_name='\u05e0\u05d5\u05e1\u05d7\u05d4')),
                ('premises', models.CharField(max_length=300, verbose_name='\u05d4\u05e0\u05d7\u05d5\u05ea')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.Chapter', verbose_name='\u05e4\u05e8\u05e7')),
                ('followup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logic.DeductionQuestion', verbose_name='\u05e9\u05d0\u05dc\u05ea \u05d4\u05de\u05e9\u05da')),
            ],
            options={
                'ordering': ['number'],
                'abstract': False,
                'verbose_name': '\u05e9\u05d0\u05dc\u05ea \u05d3\u05d3\u05d5\u05e7\u05e6\u05d9\u05d4',
                'verbose_name_plural': '\u05e9\u05d0\u05dc\u05d5\u05ea \u05d3\u05d3\u05d5\u05e7\u05e6\u05d9\u05d4',
            },
        ),
        migrations.CreateModel(
            name='FormulationAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='\u05d8\u05e7\u05e1\u05d8')),
            ],
            options={
                'abstract': False,
                'verbose_name': '\u05ea\u05e9\u05d5\u05d1\u05d4',
                'verbose_name_plural': '\u05ea\u05e9\u05d5\u05d1\u05d5\u05ea',
            },
        ),
        migrations.CreateModel(
            name='FormulationQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='\u05de\u05e1\u05e4\u05e8')),
                ('text', models.TextField(verbose_name='\u05d8\u05e7\u05e1\u05d8')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.Chapter', verbose_name='\u05e4\u05e8\u05e7')),
                ('followup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logic.FormulationQuestion', verbose_name='\u05e9\u05d0\u05dc\u05ea \u05d4\u05de\u05e9\u05da')),
            ],
            options={
                'ordering': ['number'],
                'abstract': False,
                'verbose_name': '\u05e9\u05d0\u05dc\u05ea \u05d4\u05e6\u05e8\u05e0\u05d4',
                'verbose_name_plural': '\u05e9\u05d0\u05dc\u05d5\u05ea \u05d4\u05e6\u05e8\u05e0\u05d4',
            },
        ),
        migrations.CreateModel(
            name='OpenQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='\u05de\u05e1\u05e4\u05e8')),
                ('text', models.TextField(verbose_name='\u05d8\u05e7\u05e1\u05d8')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.Chapter', verbose_name='\u05e4\u05e8\u05e7')),
                ('followup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logic.OpenQuestion', verbose_name='\u05e9\u05d0\u05dc\u05ea \u05d4\u05de\u05e9\u05da')),
            ],
            options={
                'ordering': ['number'],
                'abstract': False,
                'verbose_name': '\u05e9\u05d0\u05dc\u05ea \u05e4\u05ea\u05d5\u05d7\u05d4',
                'verbose_name_plural': '\u05e9\u05d0\u05dc\u05d5\u05ea \u05e4\u05ea\u05d5\u05d7\u05d5\u05ea',
            },
        ),
        migrations.CreateModel(
            name='TruthTableQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='\u05de\u05e1\u05e4\u05e8')),
                ('formula', models.CharField(max_length=30, verbose_name='\u05e0\u05d5\u05e1\u05d7\u05d4')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.Chapter', verbose_name='\u05e4\u05e8\u05e7')),
                ('followup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logic.TruthTableQuestion', verbose_name='\u05e9\u05d0\u05dc\u05ea \u05d4\u05de\u05e9\u05da')),
            ],
            options={
                'ordering': ['number'],
                'abstract': False,
                'verbose_name': '\u05e9\u05d0\u05dc\u05ea \u05d8\u05d1\u05dc\u05ea \u05d0\u05de\u05ea',
                'verbose_name_plural': '\u05e9\u05d0\u05dc\u05d5\u05ea \u05d8\u05d1\u05dc\u05ea \u05d0\u05de\u05ea',
            },
        ),
        migrations.AddField(
            model_name='formulationanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.FormulationQuestion', verbose_name='\u05e9\u05d0\u05dc\u05d4'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.ChoiceQuestion', verbose_name='\u05e9\u05d0\u05dc\u05d4'),
        ),
        migrations.AlterUniqueTogether(
            name='truthtablequestion',
            unique_together=set([('chapter', 'number')]),
        ),
        migrations.AlterUniqueTogether(
            name='openquestion',
            unique_together=set([('chapter', 'number')]),
        ),
        migrations.AlterUniqueTogether(
            name='formulationquestion',
            unique_together=set([('chapter', 'number')]),
        ),
        migrations.AlterUniqueTogether(
            name='deductionquestion',
            unique_together=set([('chapter', 'number')]),
        ),
        migrations.AlterUniqueTogether(
            name='choicequestion',
            unique_together=set([('chapter', 'number')]),
        ),
    ]
