# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-22 14:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='\u05de\u05e1\u05e4\u05e8')),
                ('title', models.CharField(max_length=30, verbose_name='\u05db\u05d5\u05ea\u05e8\u05ea')),
            ],
            options={
                'ordering': ['number'],
                'verbose_name': '\u05e4\u05e8\u05e7',
                'verbose_name_plural': '\u05e4\u05e8\u05e7\u05d9\u05dd',
            },
        ),
        migrations.CreateModel(
            name='ChapterSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.PositiveIntegerField(verbose_name='\u05e0\u05e1\u05d9\u05d5\u05e0\u05d5\u05ea')),
                ('ongoing', models.BooleanField()),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='\u05d6\u05de\u05df \u05d4\u05d2\u05e9\u05d4')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.Chapter', verbose_name='\u05e4\u05e8\u05e7')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u05de\u05e9\u05ea\u05de\u05e9')),
            ],
            options={
                'ordering': ['chapter'],
                'verbose_name': '\u05d4\u05d2\u05e9\u05ea \u05de\u05e9\u05ea\u05de\u05e9',
                'verbose_name_plural': '\u05d4\u05d2\u05e9\u05d5\u05ea \u05de\u05e9\u05ea\u05de\u05e9\u05d9\u05dd',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='\u05d8\u05e7\u05e1\u05d8')),
                ('is_correct', models.BooleanField(default=False, verbose_name='\u05ea\u05e9\u05d5\u05d1\u05ea \u05e0\u05db\u05d5\u05e0\u05d4?')),
            ],
            options={
                'verbose_name': '\u05d1\u05d7\u05d9\u05e8\u05d4',
                'verbose_name_plural': '\u05d1\u05d7\u05d9\u05e8\u05d5\u05ea',
            },
        ),
        migrations.CreateModel(
            name='ChoiceQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=0, null=True, verbose_name='\u05de\u05e1\u05e4\u05e8')),
                ('text', models.TextField(verbose_name='\u05d8\u05e7\u05e1\u05d8')),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logic.Chapter', verbose_name='\u05e4\u05e8\u05e7')),
            ],
            options={
                'ordering': ['number'],
                'abstract': False,
                'verbose_name': '\u05e9\u05d0\u05dc\u05ea \u05d1\u05d7\u05d9\u05e8\u05d4',
                'verbose_name_plural': '\u05e9\u05d0\u05dc\u05d5\u05ea \u05d1\u05d7\u05d9\u05e8\u05d4',
            },
        ),
        migrations.CreateModel(
            name='DeductionQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=0, null=True, verbose_name='\u05de\u05e1\u05e4\u05e8')),
                ('formula', models.CharField(max_length=60, verbose_name='\u05d8\u05d9\u05e2\u05d5\u05df')),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logic.Chapter', verbose_name='\u05e4\u05e8\u05e7')),
            ],
            options={
                'ordering': ['number'],
                'abstract': False,
                'verbose_name': '\u05e9\u05d0\u05dc\u05ea \u05d3\u05d3\u05d5\u05e7\u05e6\u05d9\u05d4',
                'verbose_name_plural': '\u05e9\u05d0\u05dc\u05d5\u05ea \u05d3\u05d3\u05d5\u05e7\u05e6\u05d9\u05d4',
            },
        ),
        migrations.CreateModel(
            name='FormulationAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(max_length=60, verbose_name='\u05e0\u05d5\u05e1\u05d7\u05d4')),
            ],
            options={
                'verbose_name': '\u05ea\u05e9\u05d5\u05d1\u05d4',
                'verbose_name_plural': '\u05ea\u05e9\u05d5\u05d1\u05d5\u05ea',
            },
        ),
        migrations.CreateModel(
            name='FormulationQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=0, null=True, verbose_name='\u05de\u05e1\u05e4\u05e8')),
                ('text', models.TextField(verbose_name='\u05d8\u05e7\u05e1\u05d8')),
                ('followup', models.CharField(choices=[('N', '\u05dc\u05dc\u05d0'), ('T', '\u05d8\u05d1\u05dc\u05ea \u05d0\u05de\u05ea'), ('D', '\u05d3\u05d3\u05d5\u05e7\u05e6\u05d9\u05d4')], default='N', max_length=1, verbose_name='\u05e9\u05d0\u05dc\u05ea \u05d4\u05de\u05e9\u05da')),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logic.Chapter', verbose_name='\u05e4\u05e8\u05e7')),
            ],
            options={
                'ordering': ['number'],
                'abstract': False,
                'verbose_name': '\u05e9\u05d0\u05dc\u05ea \u05d4\u05e6\u05e8\u05e0\u05d4',
                'verbose_name_plural': '\u05e9\u05d0\u05dc\u05d5\u05ea \u05d4\u05e6\u05e8\u05e0\u05d4',
            },
        ),
        migrations.CreateModel(
            name='ModelQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=0, null=True, verbose_name='\u05de\u05e1\u05e4\u05e8')),
                ('table_type', models.CharField(choices=[('F', '\u05e0\u05d5\u05e1\u05d7\u05d4'), ('S', '\u05e7\u05d1\u05d5\u05e6\u05d4'), ('A', '\u05d8\u05d9\u05e2\u05d5\u05df')], max_length=1, null=True, verbose_name='\u05e1\u05d5\u05d2')),
                ('formula', models.CharField(max_length=60, null=True, verbose_name='\u05e0\u05d5\u05e1\u05d7\u05d4/\u05d8\u05d9\u05e2\u05d5\u05df/\u05e7\u05d1\u05d5\u05e6\u05d4')),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logic.Chapter', verbose_name='\u05e4\u05e8\u05e7')),
            ],
            options={
                'ordering': ['number'],
                'abstract': False,
                'verbose_name': '\u05e9\u05d0\u05dc\u05ea \u05e4\u05e9\u05e8',
                'verbose_name_plural': '\u05e9\u05d0\u05dc\u05d5\u05ea \u05e4\u05e9\u05e8',
            },
        ),
        migrations.CreateModel(
            name='OpenQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=0, null=True, verbose_name='\u05de\u05e1\u05e4\u05e8')),
                ('text', models.TextField(verbose_name='\u05d8\u05e7\u05e1\u05d8')),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logic.Chapter', verbose_name='\u05e4\u05e8\u05e7')),
            ],
            options={
                'ordering': ['number'],
                'abstract': False,
                'verbose_name': '\u05e9\u05d0\u05dc\u05ea \u05e4\u05ea\u05d5\u05d7\u05d4',
                'verbose_name_plural': '\u05e9\u05d0\u05dc\u05d5\u05ea \u05e4\u05ea\u05d5\u05d7\u05d5\u05ea',
            },
        ),
        migrations.CreateModel(
            name='TruthTableQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=0, null=True, verbose_name='\u05de\u05e1\u05e4\u05e8')),
                ('table_type', models.CharField(choices=[('F', '\u05e0\u05d5\u05e1\u05d7\u05d4'), ('S', '\u05e7\u05d1\u05d5\u05e6\u05d4'), ('A', '\u05d8\u05d9\u05e2\u05d5\u05df')], max_length=1, null=True, verbose_name='\u05e1\u05d5\u05d2')),
                ('formula', models.CharField(max_length=60, null=True, verbose_name='\u05e0\u05d5\u05e1\u05d7\u05d4/\u05d8\u05d9\u05e2\u05d5\u05df/\u05e7\u05d1\u05d5\u05e6\u05d4')),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logic.Chapter', verbose_name='\u05e4\u05e8\u05e7')),
            ],
            options={
                'ordering': ['number'],
                'abstract': False,
                'verbose_name': '\u05e9\u05d0\u05dc\u05ea \u05d8\u05d1\u05dc\u05ea \u05d0\u05de\u05ea',
                'verbose_name_plural': '\u05e9\u05d0\u05dc\u05d5\u05ea \u05d8\u05d1\u05dc\u05ea \u05d0\u05de\u05ea',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField(verbose_name='\u05de\u05e1\u05e4\u05e8 \u05e9\u05d0\u05dc\u05d4')),
                ('correct', models.BooleanField(verbose_name='\u05ea\u05e9\u05d5\u05d1\u05d4 \u05e0\u05db\u05d5\u05e0\u05d4')),
                ('answer', models.TextField()),
                ('is_followup', models.BooleanField(default=False)),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='\u05d6\u05de\u05df')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.Chapter', verbose_name='\u05e4\u05e8\u05e7')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.ChapterSubmission', verbose_name='\u05d4\u05d2\u05e9\u05ea \u05e4\u05e8\u05e7')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u05de\u05e9\u05ea\u05de\u05e9')),
            ],
            options={
                'verbose_name': '\u05ea\u05e9\u05d5\u05d1\u05ea \u05de\u05e9\u05ea\u05de\u05e9',
                'verbose_name_plural': '*\u05ea\u05e9\u05d5\u05d1\u05d5\u05ea \u05de\u05e9\u05ea\u05de\u05e9\u05d9\u05dd',
            },
        ),
        migrations.AddField(
            model_name='formulationanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.FormulationQuestion', verbose_name='\u05e9\u05d0\u05dc\u05d4'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.ChoiceQuestion', verbose_name='\u05e9\u05d0\u05dc\u05d4'),
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together=set([('chapter', 'user', 'question_number', 'is_followup')]),
        ),
        migrations.AlterUniqueTogether(
            name='truthtablequestion',
            unique_together=set([('chapter', 'formula')]),
        ),
        migrations.AlterUniqueTogether(
            name='modelquestion',
            unique_together=set([('chapter', 'formula')]),
        ),
        migrations.AlterUniqueTogether(
            name='deductionquestion',
            unique_together=set([('chapter', 'formula')]),
        ),
        migrations.AlterUniqueTogether(
            name='chaptersubmission',
            unique_together=set([('chapter', 'user')]),
        ),
    ]
