# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-26 15:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=2, verbose_name='\u05de\u05e1\u05e4\u05e8 \u05e7\u05d1\u05d5\u05e6\u05d4')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='formulationanswer',
            name='formula',
            field=models.CharField(max_length=60, verbose_name='\u05e0\u05d5\u05e1\u05d7\u05d4/\u05d8\u05d9\u05e2\u05d5\u05df/\u05e7\u05d1\u05d5\u05e6\u05d4'),
        ),
        migrations.AlterField(
            model_name='formulationquestion',
            name='followup',
            field=models.CharField(choices=[('N', '\u05dc\u05dc\u05d0'), ('T', '\u05d8\u05d1\u05dc\u05ea \u05d0\u05de\u05ea'), ('D', '\u05d3\u05d3\u05d5\u05e7\u05e6\u05d9\u05d4'), ('M', '\u05e4\u05e9\u05e8')], default='N', max_length=1, verbose_name='\u05e9\u05d0\u05dc\u05ea \u05d4\u05de\u05e9\u05da'),
        ),
    ]
