# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 13:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.PositiveIntegerField(verbose_name='\u05de\u05e1\u05e4\u05e8 \u05e9\u05d0\u05dc\u05d4')),
                ('correct', models.BooleanField(verbose_name='\u05ea\u05e9\u05d5\u05d1\u05d4 \u05e0\u05db\u05d5\u05e0\u05d4')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.Chapter', verbose_name='\u05e4\u05e8\u05e7')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u05de\u05e9\u05ea\u05de\u05e9')),
            ],
            options={
                'abstract': False,
                'verbose_name': '\u05ea\u05e9\u05d5\u05d1\u05ea \u05de\u05e9\u05ea\u05de\u05e9',
                'verbose_name_plural': '\u05ea\u05e9\u05d5\u05d1\u05d5\u05ea \u05de\u05e9\u05ea\u05de\u05e9',
            },
        ),
    ]
