# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0002_useranswer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together=set([('chapter', 'user', 'question_number')]),
        ),
    ]
