# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-27 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0002_auto_20160826_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='\u05d8\u05e7\u05e1\u05d8')),
                ('upload', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m')),
            ],
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '\u05e4\u05e8\u05d5\u05e4\u05d9\u05dc', 'verbose_name_plural': '\u05e4\u05e8\u05d5\u05e4\u05d9\u05dc\u05d9\u05dd'},
        ),
    ]
