# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-27 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0003_auto_20160827_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='openanswer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logic.OpenQuestion', verbose_name='\u05e9\u05d0\u05dc\u05d4'),
            preserve_default=False,
        ),
    ]
