# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 08:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logic', '0003_auto_20160617_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.Chapter', verbose_name='\u05e4\u05e8\u05e7')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u05de\u05e9\u05ea\u05de\u05e9')),
            ],
            options={
                'abstract': False,
                'verbose_name': '\u05e4\u05ea\u05e8\u05d5\u05df \u05de\u05e9\u05ea\u05de\u05e9',
                'verbose_name_plural': '\u05e4\u05ea\u05e8\u05d5\u05e0\u05d5\u05ea \u05de\u05e9\u05ea\u05de\u05e9\u05d9\u05dd',
            },
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': '\u05ea\u05e9\u05d5\u05d1\u05ea \u05de\u05e9\u05ea\u05de\u05e9', 'verbose_name_plural': '\u05ea\u05e9\u05d5\u05d1\u05d5\u05ea \u05de\u05e9\u05ea\u05de\u05e9\u05d9\u05dd'},
        ),
        migrations.AlterUniqueTogether(
            name='userchapter',
            unique_together=set([('chapter', 'user')]),
        ),
    ]
