# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-28 15:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logic', '0004_openanswer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='openanswer',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='\u05e0\u05d1\u05d3\u05e7'),
        ),
        migrations.AddField(
            model_name='openanswer',
            name='user_answer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
