# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0005_useranswer_user_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='user_chapter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='logic.UserChapter', verbose_name='\u05e4\u05ea\u05e8\u05d5\u05df \u05e4\u05e8\u05e7'),
            preserve_default=False,
        ),
    ]
