# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-18 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import logic.models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0006_auto_20160618_1013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': '\u05ea\u05e9\u05d5\u05d1\u05ea \u05de\u05e9\u05ea\u05de\u05e9', 'verbose_name_plural': '*\u05ea\u05e9\u05d5\u05d1\u05d5\u05ea \u05de\u05e9\u05ea\u05de\u05e9\u05d9\u05dd'},
        ),
        migrations.AlterModelOptions(
            name='userchapter',
            options={'verbose_name': '\u05e4\u05ea\u05e8\u05d5\u05df \u05de\u05e9\u05ea\u05de\u05e9', 'verbose_name_plural': '*\u05e4\u05ea\u05e8\u05d5\u05e0\u05d5\u05ea \u05de\u05e9\u05ea\u05de\u05e9\u05d9\u05dd'},
        ),
        migrations.AlterField(
            model_name='deductionquestion',
            name='formula',
            field=models.CharField(max_length=30, validators=[logic.models.validate_formula], verbose_name='\u05e0\u05d5\u05e1\u05d7\u05d4'),
        ),
        migrations.AlterField(
            model_name='truthtablequestion',
            name='formula',
            field=models.CharField(max_length=30, validators=[logic.models.validate_formula], verbose_name='\u05e0\u05d5\u05e1\u05d7\u05d4'),
        ),
        migrations.AlterUniqueTogether(
            name='choicequestion',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='deductionquestion',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='formulationquestion',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='openquestion',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='truthtablequestion',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='deductionquestion',
            name='premises',
        ),
    ]
