# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0007_auto_20160618_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='truthtablequestion',
            name='table_type',
            field=models.CharField(choices=[('F', '\u05e0\u05d5\u05e1\u05d7\u05d4'), ('S', '\u05e7\u05d1\u05d5\u05e6\u05d4'), ('A', '\u05d8\u05d9\u05e2\u05d5\u05df')], default='F', max_length=1),
        ),
    ]
