# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-03 11:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0007_auto_20160831_1935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openanswer',
            options={'verbose_name': '\u05ea\u05e9\u05d5\u05d1\u05d4 \u05e4\u05ea\u05d5\u05d7\u05d4', 'verbose_name_plural': '*\u05ea\u05e9\u05d5\u05d1\u05d5\u05ea \u05e4\u05ea\u05d5\u05d7\u05d5\u05ea'},
        ),
    ]
