# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-03 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0008_auto_20160903_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chaptersubmission',
            options={'ordering': ['chapter'], 'verbose_name': '\u05d4\u05d2\u05e9\u05ea \u05de\u05e9\u05ea\u05de\u05e9', 'verbose_name_plural': '[\u05d4\u05d2\u05e9\u05d5\u05ea \u05de\u05e9\u05ea\u05de\u05e9\u05d9\u05dd]'},
        ),
        migrations.AlterModelOptions(
            name='openanswer',
            options={'verbose_name': '\u05ea\u05e9\u05d5\u05d1\u05d4 \u05e4\u05ea\u05d5\u05d7\u05d4', 'verbose_name_plural': '[\u05ea\u05e9\u05d5\u05d1\u05d5\u05ea \u05e4\u05ea\u05d5\u05d7\u05d5\u05ea]'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': '\u05ea\u05e9\u05d5\u05d1\u05ea \u05de\u05e9\u05ea\u05de\u05e9', 'verbose_name_plural': '[\u05ea\u05e9\u05d5\u05d1\u05d5\u05ea \u05de\u05e9\u05ea\u05de\u05e9\u05d9\u05dd]'},
        ),
        migrations.AddField(
            model_name='openanswer',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='\u05d4\u05e2\u05e8\u05d5\u05ea'),
        ),
        migrations.AddField(
            model_name='openanswer',
            name='grade',
            field=models.FloatField(null=True, verbose_name='\u05e0\u05d9\u05e7\u05d5\u05d3'),
        ),
        migrations.AlterField(
            model_name='openanswer',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m', verbose_name='\u05e7\u05d5\u05d1\u05e5'),
        ),
    ]
