# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import logic.models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0008_truthtablequestion_table_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deductionquestion',
            name='formula',
        ),
        migrations.RemoveField(
            model_name='truthtablequestion',
            name='formula',
        ),
        migrations.AddField(
            model_name='deductionquestion',
            name='text',
            field=models.CharField(default='p', max_length=30, validators=[logic.models.validate_argument], verbose_name='\u05d8\u05d9\u05e2\u05d5\u05df'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='truthtablequestion',
            name='text',
            field=models.CharField(default='p', max_length=30, validators=[logic.models.validate_truth_table], verbose_name='\u05d8\u05e7\u05e1\u05d8'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='truthtablequestion',
            name='table_type',
            field=models.CharField(choices=[('F', '\u05e0\u05d5\u05e1\u05d7\u05d4'), ('S', '\u05e7\u05d1\u05d5\u05e6\u05d4'), ('A', '\u05d8\u05d9\u05e2\u05d5\u05df')], default='F', max_length=1, verbose_name='\u05e1\u05d5\u05d2'),
        ),
    ]
