# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-03 15:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0010_auto_20160903_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openanswer',
            name='grade',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MaxValueValidator(1.0), django.core.validators.MinValueValidator(0.0)], verbose_name='\u05e0\u05d9\u05e7\u05d5\u05d3'),
        ),
    ]
