# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0011_auto_20160624_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truthtablequestion',
            name='formula',
            field=models.CharField(max_length=60, verbose_name='\u05d8\u05e7\u05e1\u05d8'),
        ),
    ]
