# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-03 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0011_auto_20160903_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openanswer',
            name='checked',
        ),
    ]
