# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-04 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0012_remove_openanswer_checked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField()),
                ('user_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.UserAnswer')),
            ],
        ),
        migrations.AlterField(
            model_name='openanswer',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='\u05d4\u05e2\u05e8\u05d5\u05ea (\u05d0\u05d5\u05e4\u05e6\u05d9\u05d5\u05e0\u05dc\u05d9)'),
        ),
    ]
