# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-03 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0013_auto_20160624_1043'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserChapter',
            new_name='ChapterSubmission',
        ),
        migrations.AlterModelOptions(
            name='chaptersubmission',
            options={'verbose_name': '\u05d4\u05d2\u05e9\u05ea \u05de\u05e9\u05ea\u05de\u05e9', 'verbose_name_plural': '\u05d4\u05d2\u05e9\u05d5\u05ea \u05de\u05e9\u05ea\u05de\u05e9\u05d9\u05dd'},
        ),
    ]
