# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0015_auto_20160703_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaptersubmission',
            name='attempt',
            field=models.PositiveIntegerField(default=1, verbose_name='\u05e0\u05e1\u05d9\u05d5\u05df'),
            preserve_default=False,
        ),
    ]
