# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-09 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0015_auto_20160909_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaptersubmission',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logic.Chapter', verbose_name='\u05e4\u05e8\u05e7'),
        ),
        migrations.AlterField(
            model_name='openanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logic.OpenQuestion', verbose_name='\u05e9\u05d0\u05dc\u05d4'),
        ),
    ]
