# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0016_chaptersubmission_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaptersubmission',
            name='ongoing',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chaptersubmission',
            name='attempt',
            field=models.PositiveIntegerField(verbose_name='\u05e0\u05e1\u05d9\u05d5\u05e0\u05d5\u05ea'),
        ),
    ]
