# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-09 19:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0016_auto_20160909_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logic.Chapter', verbose_name='\u05e4\u05e8\u05e7'),
        ),
    ]
