# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-17 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import logic.models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0017_auto_20160715_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulationanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.FormulationQuestion', validators=[logic.models.validate_formula], verbose_name='\u05e9\u05d0\u05dc\u05d4'),
        ),
    ]
