# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-17 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0018_auto_20160717_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulationanswer',
            name='text',
        ),
        migrations.AddField(
            model_name='formulationanswer',
            name='formula',
            field=models.CharField(default='p', max_length=60, verbose_name='\u05e0\u05d5\u05e1\u05d7\u05d4'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deductionquestion',
            name='formula',
            field=models.CharField(max_length=60, verbose_name='\u05d8\u05d9\u05e2\u05d5\u05df'),
        ),
        migrations.AlterField(
            model_name='formulationanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.FormulationQuestion', verbose_name='\u05e9\u05d0\u05dc\u05d4'),
        ),
    ]
