# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-10 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0018_auto_20160909_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(max_length=40, verbose_name='\u05db\u05d5\u05ea\u05e8\u05ea'),
        ),
    ]
