# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0019_auto_20160717_2307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chaptersubmission',
            options={'ordering': ['chapter'], 'verbose_name': '\u05d4\u05d2\u05e9\u05ea \u05de\u05e9\u05ea\u05de\u05e9', 'verbose_name_plural': '\u05d4\u05d2\u05e9\u05d5\u05ea \u05de\u05e9\u05ea\u05de\u05e9\u05d9\u05dd'},
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
