# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-12 15:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import logic.models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0019_auto_20160910_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='number',
            field=models.DecimalField(decimal_places=1, max_digits=3, unique=True, validators=[django.core.validators.MaxValueValidator(100.0), django.core.validators.MinValueValidator(1.0)], verbose_name='\u05de\u05e1\u05e4\u05e8'),
        ),
        migrations.AlterField(
            model_name='openanswer',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=logic.models.name_file, verbose_name='\u05e7\u05d5\u05d1\u05e5'),
        ),
    ]
