# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-24 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0020_auto_20160718_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaptersubmission',
            name='time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u05d6\u05de\u05df \u05d4\u05d2\u05e9\u05d4'),
        ),
    ]
