# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-12 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0021_chapter_gen_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='gen_title',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='\u05db\u05d5\u05ea\u05e8\u05ea \u05db\u05dc\u05dc\u05d9\u05ea (\u05d0\u05d5\u05e4\u05e6\u05d9\u05d5\u05e0\u05dc\u05d9. \u05e9\u05dd \u05d6\u05d4 \u05d9\u05e9\u05de\u05e9 \u05dc\u05ea\u05e6\u05d5\u05d2\u05d4 \u05d1\u05de\u05e1\u05da \u05d4\u05e8\u05d0\u05e9\u05d9 \u05e2\u05d1\u05d5\u05e8 \u05e4\u05e8\u05e7\u05d9\u05dd \u05de\u05e8\u05d5\u05d1\u05d9 \u05d7\u05dc\u05e7\u05d9\u05dd)'),
        ),
    ]
