# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-30 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0022_auto_20160730_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulationanswer',
            name='followup',
        ),
        migrations.AddField(
            model_name='formulationquestion',
            name='followup',
            field=models.CharField(choices=[('N', '\u05dc\u05dc\u05d0'), ('T', '\u05d8\u05d1\u05dc\u05ea \u05d0\u05de\u05ea'), ('D', '\u05d3\u05d3\u05d5\u05e7\u05e6\u05d9\u05d4')], default='N', max_length=1, verbose_name='\u05e9\u05d0\u05dc\u05ea \u05d4\u05de\u05e9\u05da'),
        ),
    ]
