# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-31 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0023_auto_20160730_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='is_followup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='truthtablequestion',
            name='formula',
            field=models.CharField(max_length=60, verbose_name='\u05e0\u05d5\u05e1\u05d7\u05d4/\u05d8\u05d9\u05e2\u05d5\u05df/\u05e7\u05d1\u05d5\u05e6\u05d4'),
        ),
        migrations.AlterField(
            model_name='truthtablequestion',
            name='table_type',
            field=models.CharField(choices=[('F', '\u05e0\u05d5\u05e1\u05d7\u05d4'), ('S', '\u05e7\u05d1\u05d5\u05e6\u05d4'), ('A', '\u05d8\u05d9\u05e2\u05d5\u05df')], max_length=1, verbose_name='\u05e1\u05d5\u05d2'),
        ),
    ]
