# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-29 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0023_chapter_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='url',
        ),
    ]
