# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-31 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0024_auto_20160731_1635'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together=set([('chapter', 'user', 'question_number', 'is_followup')]),
        ),
    ]
