# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-01 14:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0024_remove_chapter_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='id_num',
            field=models.CharField(default='123456789', max_length=9, validators=[django.core.validators.RegexValidator(message='\u05de\u05e1\u05e4\u05e8 \u05ea.\u05d6 \u05e6\u05e8\u05d9\u05da \u05dc\u05d4\u05d9\u05d5\u05ea \u05d1\u05d0\u05d5\u05e8\u05da 9 \u05e1\u05e4\u05e8\u05d5\u05ea', regex='^\\d{9}$')], verbose_name='\u05de\u05e1\u05e4\u05e8 \u05ea.\u05d6'),
            preserve_default=False,
        ),
    ]
