# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-01 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0025_userprofile_id_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(default='0618101201', max_length=30, verbose_name='\u05de\u05e1\u05e4\u05e8 \u05e7\u05d5\u05e8\u05e1')),
                ('max_group_id', models.CharField(default='09', max_length=2, verbose_name='\u05de\u05e1\u05e4\u05e8 \u05e7\u05d1\u05d5\u05e6\u05d4 \u05de\u05e7\u05e1\u05d9\u05de\u05dc\u05d9')),
                ('max_attempts', models.PositiveIntegerField(default=3, verbose_name='\u05de\u05e1\u05e4\u05e8 \u05e0\u05e1\u05d9\u05d5\u05e0\u05d5\u05ea \u05de\u05e7\u05e1\u05d9\u05de\u05dc\u05d9 \u05dc\u05d4\u05d2\u05e9\u05d4')),
                ('max_file_size', models.PositiveIntegerField(default=3145728, verbose_name='\u05d2\u05d5\u05d3\u05dc \u05e7\u05d5\u05d1\u05e5 \u05de\u05e7\u05e1\u05d9\u05de\u05dc\u05d9')),
                ('ldap_enabled', models.BooleanField(default=True, verbose_name='\u05d0\u05d9\u05de\u05d5\u05ea \u05de\u05e9\u05ea\u05de\u05e9\u05d9 \u05d0\u05d5\u05e0\u05d9\u05d1\u05e8\u05e1\u05d9\u05d8\u05d4')),
            ],
        ),
        migrations.AlterModelOptions(
            name='chaptersubmission',
            options={'ordering': ['chapter'], 'verbose_name': '\u05d4\u05d2\u05e9\u05ea \u05de\u05e9\u05ea\u05de\u05e9', 'verbose_name_plural': '\u05d4\u05d2\u05e9\u05d5\u05ea \u05de\u05e9\u05ea\u05de\u05e9\u05d9\u05dd'},
        ),
        migrations.AlterModelOptions(
            name='openanswer',
            options={'verbose_name': '\u05ea\u05e9\u05d5\u05d1\u05d4 \u05e4\u05ea\u05d5\u05d7\u05d4', 'verbose_name_plural': '\u05ea\u05e9\u05d5\u05d1\u05d5\u05ea \u05e4\u05ea\u05d5\u05d7\u05d5\u05ea'},
        ),
    ]
