# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-31 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0025_auto_20160731_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u05d6\u05de\u05df'),
        ),
    ]
