# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-22 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0026_useranswer_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelQuestion',
            fields=[
                ('truthtablequestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='logic.TruthTableQuestion')),
            ],
            options={
                'ordering': ['number'],
                'abstract': False,
                'verbose_name': '\u05e9\u05d0\u05dc\u05ea \u05e4\u05e9\u05e8',
                'verbose_name_plural': '\u05e9\u05d0\u05dc\u05d5\u05ea \u05e4\u05e9\u05e8',
            },
            bases=('logic.truthtablequestion',),
        ),
    ]
