# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-01 21:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0026_auto_20161001_2330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chaptersubmission',
            options={'ordering': ['chapter'], 'verbose_name': '\u05d4\u05d2\u05e9\u05d4', 'verbose_name_plural': '\u05d4\u05d2\u05e9\u05d5\u05ea'},
        ),
        migrations.AlterModelOptions(
            name='globalsettings',
            options={'verbose_name': '\u05d4\u05d2\u05d3\u05e8\u05d5\u05ea \u05db\u05dc\u05dc\u05d9\u05d5\u05ea', 'verbose_name_plural': '\u05d4\u05d2\u05d3\u05e8\u05d5\u05ea \u05db\u05dc\u05dc\u05d9\u05d5\u05ea'},
        ),
        migrations.AlterField(
            model_name='formulationquestion',
            name='followup',
            field=models.CharField(choices=[('N', '\u05dc\u05dc\u05d0'), ('T', '\u05d8\u05d1\u05dc\u05ea \u05d0\u05de\u05ea'), ('D', '\u05d3\u05d3\u05d5\u05e7\u05e6\u05d9\u05d4')], default='N', max_length=1, verbose_name='\u05e9\u05d0\u05dc\u05ea \u05d4\u05de\u05e9\u05da'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='course_id',
            field=models.CharField(default='0618101201', max_length=30, validators=[django.core.validators.RegexValidator(message='\u05d9\u05e9 \u05dc\u05d4\u05d6\u05d9\u05df \u05e1\u05e4\u05e8\u05d5\u05ea \u05d1\u05dc\u05d1\u05d3', regex='^\\d+$')], verbose_name='\u05de\u05e1\u05e4\u05e8 \u05e7\u05d5\u05e8\u05e1'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='max_attempts',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='\u05de\u05e1\u05e4\u05e8 \u05e0\u05e1\u05d9\u05d5\u05e0\u05d5\u05ea \u05de\u05e7\u05e1\u05d9\u05de\u05dc\u05d9 \u05dc\u05d4\u05d2\u05e9\u05d4'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='max_file_size',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)], verbose_name='\u05d2\u05d5\u05d3\u05dc \u05de\u05e7\u05e1\u05d9\u05de\u05dc\u05d9 \u05dc\u05d4\u05e2\u05dc\u05d0\u05ea \u05e7\u05d5\u05d1\u05e5 (MB)'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='max_group_id',
            field=models.CharField(default='09', max_length=2, validators=[django.core.validators.RegexValidator(message='\u05d9\u05e9 \u05dc\u05d4\u05d6\u05d9\u05df \u05e9\u05ea\u05d9 \u05e1\u05e4\u05e8\u05d5\u05ea', regex='^\\d{2}$')], verbose_name='\u05de\u05e1\u05e4\u05e8 \u05e7\u05d1\u05d5\u05e6\u05d4 \u05de\u05e7\u05e1\u05d9\u05de\u05dc\u05d9'),
        ),
    ]
