# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-07 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0027_auto_20161002_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='openquestion',
            name='has_file',
            field=models.BooleanField(default=True, verbose_name='\u05d0\u05e4\u05e9\u05e8 \u05d4\u05e2\u05dc\u05d0\u05ea \u05e7\u05d5\u05d1\u05e5'),
        ),
    ]
