#! /bin/bash

echo '['`date +'%Y-%m-%d %H:%M:%S'`']'
echo 'Building...'

echo 'Minifying js...'
cd /home/eliranh/frege/frege2/frege/logic/static/logic/js
uglifyjs requests.js -m toplevel -c -r 'postAns' > requests.min.js
uglifyjs deduction.js -m toplevel -c -r 'oncheck,addRow' > deduction.min.js
./minify
cd - > /dev/null

echo 'Minifying css...'
cd /home/eliranh/frege/frege2/frege/logic/static/logic/css
minify --output mycss.min.css mycss.css > /dev/null
cd - > /dev/null

if [ $# -eq 0 ] || [ $1 != 'notest' ]
then
    echo 'Running tests (py)...'
    python tests.py

    echo 'Running tests (js)...'
    cd /home/eliranh/frege/frege2/frege/logic/static/logic/js
    python js_test_setup.py
    node tests.js
    cd - > /dev/null
fi

echo 'Build done'
echo '['`date +'%Y-%m-%d %H:%M:%S'`']'
